/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.runner;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication(scanBasePackages = "com.github.lette1394")
public class Spring {
  public static void main(String[] args) {
    SpringApplication.run(Spring.class, args);
  }
}
